# Generated by Django 2.0.1 on 2018-01-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180114_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionchoicerel',
            old_name='userid',
            new_name='user',
        ),
    ]
